/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jiangchenyang' at '7/4/16 3:22 PM' with Gradle 2.9
 *
 * @author jiangchenyang, @date 7/4/16 3:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
